# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('amigos', models.ManyToManyField(blank=True, related_name='_autor_amigos_+', to='bdfiltro.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clasificacion', models.FloatField()),
                ('fecha_pub', models.DateField()),
                ('autores', models.ManyToManyField(to='bdfiltro.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Publicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('num_premios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('libros', models.ManyToManyField(to='bdfiltro.Libro')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='publicadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdfiltro.Publicador'),
        ),
    ]
